### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by christinkt** [iloudaros/e-ethelodria#4]
- XAMPP
- DB Initialisation

**Comment by iloudaros** [comment]
Σε σχέση με αυτό. Επειδή έβαλα στο Default να κάνει μόνο του generate UUIDs, χρειάζεται να έχουμε όλοι MySQL 8.0.13 και πάνω. Οδηγός για windows εδώ: https://odan.github.io/2019/11/17/xampp-replacing-mariadb-with-mysql-8.html

**Comment by iloudaros** [comment]
Μεγάλη πετυχεσά. Ας ελπίσουμε ότι δεν θα το κάνουμε reopen
